{
 "title": "StoreFS / Node Metrics",
 "tags": [
  "storefs",
  "node"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(storefs_cpu_usage_percent, node)"
   },
   {
    "name": "path",
    "label": "Disk Path",
    "query": "label_values(storefs_disk_total_bytes{node=\"$node\"}, path)"
   },
   {
    "name": "device",
    "label": "Disk Device",
    "query": "label_values(storefs_disk_reads_completed_total{node=\"$node\"}, device)"
   },
   {
    "name": "interface",
    "label": "Network Interface",
    "query": "label_values(storefs_network_receive_bytes_total{node=\"$node\"}, interface)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "panels": [
    {
     "title": "CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storefs_cpu_usage_percent{node=\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storefs_memory_usage_percent{node=\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storefs_disk_usage_percent{node=\"$node\"}",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Memory Total",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storefs_memory_total_bytes{node=\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storefs_memory_used_bytes{node=\"$node\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Capacity",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storefs_disk_total_bytes{node=\"$node\"}",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Host Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storefs_host_uptime_seconds{node=\"$node\"}",
       "legendFormat": "Host Uptime"
      }
     ]
    },
    {
     "title": "Node Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storefs_node_uptime_seconds{node=\"$node\"}",
       "legendFormat": "Node Uptime"
      }
     ]
    },
    {
     "title": "Upload Object Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storefs_upload_object_start_total{node=\"$node\"}",
       "legendFormat": "Upload Total"
      }
     ]
    },
    {
     "title": "Download Object Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storefs_download_object_start_total{node=\"$node\"}",
       "legendFormat": "Download Total"
      }
     ]
    },
    {
     "title": "Multipart Create Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storefs_create_multipart_start_total{node=\"$node\"}",
       "legendFormat": "Multipart Create"
      }
     ]
    },
    {
     "title": "Multipart Complete Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storefs_complete_parts_start_total{node=\"$node\"}",
       "legendFormat": "Multipart Complete"
      }
     ]
    }
   ]
  },
  {
   "title": "Object Task",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "panels": [
    {
     "title": "Upload Object Request Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(storefs_upload_object_start_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Upload Request"
      }
     ]
    },
    {
     "title": "Upload Object Complete Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(storefs_upload_object_complete_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Upload Complete"
      }
     ]
    },
    {
     "title": "Upload Object Processing Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storefs_upload_object_start_total{node=\"$node\"} - storefs_upload_object_complete_total{node=\"$node\"}",
       "legendFormat": "Upload Processing"
      }
     ]
    },
    {
     "title": "Download Object Request Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(storefs_download_object_start_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Download Request"
      }
     ]
    },
    {
     "title": "Download Object Complete Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(storefs_download_object_complete_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Download Complete"
      }
     ]
    },
    {
     "title": "Download Object Processing Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storefs_download_object_start_total{node=\"$node\"} - storefs_download_object_complete_total{node=\"$node\"}",
       "legendFormat": "Download Processing"
      }
     ]
    },
    {
     "title": "Upload Object",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "increase(storefs_upload_object_start_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Request total"
      },
      {
       "expr": "increase(storefs_upload_object_complete_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Complete total"
      },
      {
       "expr": "storefs_upload_object_start_total{node=\"$node\"} - storefs_upload_object_complete_total{node=\"$node\"}",
       "legendFormat": "Processing"
      }
     ]
    },
    {
     "title": "Download Object",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "increase(storefs_download_object_start_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Request total"
      },
      {
       "expr": "increase(storefs_download_object_complete_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Complete total"
      },
      {
       "expr": "storefs_download_object_start_total{node=\"$node\"} - storefs_download_object_complete_total{node=\"$node\"}",
       "legendFormat": "Processing"
      }
     ]
    }
   ]
  },
  {
   "title": "Multipart Task",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "panels": [
    {
     "title": "Create Multipart",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "increase(storefs_create_multipart_start_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Request total"
      },
      {
       "expr": "increase(storefs_create_multipart_complete_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Complete total"
      },
      {
       "expr": "storefs_create_multipart_start_total{node=\"$node\"} - storefs_create_multipart_complete_total{node=\"$node\"}",
       "legendFormat": "Processing"
      }
     ]
    },
    {
     "title": "Upload Part",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "increase(storefs_upload_part_start_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Request total"
      },
      {
       "expr": "increase(storefs_upload_part_complete_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Complete total"
      },
      {
       "expr": "storefs_upload_part_start_total{node=\"$node\"} - storefs_upload_part_complete_total{node=\"$node\"}",
       "legendFormat": "Processing"
      }
     ]
    },
    {
     "title": "Complete Multipart",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "increase(storefs_complete_parts_start_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Request total"
      },
      {
       "expr": "increase(storefs_complete_parts_complete_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Complete total"
      },
      {
       "expr": "storefs_complete_parts_start_total{node=\"$node\"} - storefs_complete_parts_complete_total{node=\"$node\"}",
       "legendFormat": "Processing"
      }
     ]
    },
    {
     "title": "Abort Multipart",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "increase(storefs_abort_multipart_start_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Request total"
      },
      {
       "expr": "increase(storefs_abort_multipart_complete_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Complete total"
      },
      {
       "expr": "storefs_abort_multipart_start_total{node=\"$node\"} - storefs_abort_multipart_complete_total{node=\"$node\"}",
       "legendFormat": "Processing"
      }
     ]
    }
   ]
  },
  {
   "title": "Fragment Task",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "panels": [
    {
     "title": "Write Fragment Request Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(storefs_write_fragment_start_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Write Fragment Request"
      }
     ]
    },
    {
     "title": "Write Fragment Complete Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(storefs_write_fragment_complete_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Write Fragment Complete"
      }
     ]
    },
    {
     "title": "Write Fragment Processing Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storefs_write_fragment_start_total{node=\"$node\"} - storefs_write_fragment_complete_total{node=\"$node\"}",
       "legendFormat": "Write Fragment Processing"
      }
     ]
    },
    {
     "title": "Read Fragment Request Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(storefs_read_fragment_start_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Read Fragment Request"
      }
     ]
    },
    {
     "title": "Read Fragment Complete Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(storefs_read_fragment_complete_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Read Fragment Complete"
      }
     ]
    },
    {
     "title": "Read Fragment Processing Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "storefs_read_fragment_start_total{node=\"$node\"} - storefs_read_fragment_complete_total{node=\"$node\"}",
       "legendFormat": "Read Fragment Processing"
      }
     ]
    },
    {
     "title": "Write Fragment",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "increase(storefs_write_fragment_start_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Request total"
      },
      {
       "expr": "increase(storefs_write_fragment_complete_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Complete total"
      },
      {
       "expr": "storefs_write_fragment_start_total{node=\"$node\"} - storefs_write_fragment_complete_total{node=\"$node\"}",
       "legendFormat": "Processing"
      }
     ]
    },
    {
     "title": "Read Fragment",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "increase(storefs_read_fragment_start_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Request total"
      },
      {
       "expr": "increase(storefs_read_fragment_complete_total{node=\"$node\"}[$__rate_interval])",
       "legendFormat": "Complete total"
      },
      {
       "expr": "storefs_read_fragment_start_total{node=\"$node\"} - storefs_read_fragment_complete_total{node=\"$node\"}",
       "legendFormat": "Processing"
      }
     ]
    }
   ]
  },
  {
   "title": "Bucket Task",
   "type": "row",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 47 },
   "panels": [
    {
     "title": "Top20 Hot Buckets (Object Upload)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "topk(20, storefs_upload_hot_bucket_2m{node=\"$node\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top20 Hot Buckets (Object Download)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "targets": [
      {
       "expr": "topk(20, storefs_download_hot_bucket_2m{node=\"$node\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top20 Hot Buckets (Upload Part)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "topk(20, storefs_upload_part_hot_bucket_2m{node=\"$node\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top20 Hot Buckets (Multipart Complete)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "topk(20, storefs_multipart_complete_hot_bucket_2m{node=\"$node\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Cycles",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "go_memory_gc_cycles_count{node=\"$node\"}",
       "legendFormat": "GC Cycles"
      }
     ]
    },
    {
     "title": "GC Pause Duration",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "go_memory_gc_pause_duration{node=\"$node\"}",
       "legendFormat": "GC Pause"
      }
     ]
    },
    {
     "title": "GC CPU Fraction",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "go_memstats_gc_cpu_fraction{node=\"$node\"}",
       "legendFormat": "GC CPU"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "go_goroutines{node=\"$node\"}",
       "legendFormat": "Goroutines"
      }
     ]
    },
    {
     "title": "Go Memory Used",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "go_memory_used{node=\"$node\"}",
       "legendFormat": "Memory Used"
      }
     ]
    },
    {
     "title": "GC Cycles Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(go_memory_gc_cycles_count{node=\"$node\"}[1m])",
       "legendFormat": "GC Cycles"
      }
     ]
    },
    {
     "title": "GC Pause Duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "go_memory_gc_pause_duration{node=\"$node\"}",
       "legendFormat": "GC Pause Duration"
      }
     ]
    },
    {
     "title": "GC CPU Fraction",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "go_memstats_gc_cpu_fraction{node=\"$node\"}",
       "legendFormat": "GC CPU Fraction"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{node=\"$node\"}",
       "legendFormat": "Goroutines"
      }
     ]
    },
    {
     "title": "Go Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memory_used{node=\"$node\"}",
       "legendFormat": "Go Memory Used"
      }
     ]
    }
   ]
  },
  { "title": "CPU & Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "storefs_cpu_usage_percent{node=\"$node\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "storefs_memory_total_bytes{node=\"$node\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "storefs_memory_used_bytes{node=\"$node\"}",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Disk Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "storefs_disk_usage_percent{node=\"$node\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(storefs_disk_read_bytes_total{node=\"$node\"}[$__rate_interval])",
     "legendFormat": "Read {{device}}"
    },
    {
     "expr": "rate(storefs_disk_write_bytes_total{node=\"$node\"}[$__rate_interval])",
     "legendFormat": "Write {{device}}"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(storefs_disk_reads_completed_total{node=\"$node\"}[$__rate_interval])",
     "legendFormat": "Read {{device}}"
    },
    {
     "expr": "rate(storefs_disk_writes_completed_total{node=\"$node\"}[$__rate_interval])",
     "legendFormat": "Write {{device}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Network Traffic (bits)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(storefs_network_receive_bytes_total{node=\"$node\"}[$__rate_interval]) * 8",
     "legendFormat": "RX {{interface}}"
    },
    {
     "expr": "rate(storefs_network_transmit_bytes_total{node=\"$node\"}[$__rate_interval]) * 8",
     "legendFormat": "TX {{interface}}"
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(storefs_network_receive_packets_total{node=\"$node\"}[$__rate_interval])",
     "legendFormat": "RX {{interface}}"
    },
    {
     "expr": "rate(storefs_network_transmit_packets_total{node=\"$node\"}[$__rate_interval])",
     "legendFormat": "TX {{interface}}"
    }
   ]
  }
 ]
}