{
 "title": "StoreFS / All Nodes Summary Metrics",
 "tags": [
  "storefs",
  "cluster"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Cluster Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "panels": [
    {
     "title": "Node Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "storefs_node_uptime_seconds{}", "legendFormat": "{{node}}" }
     ]
    }
   ]
  },
  {
   "title": "Object Task",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "panels": [
    {
     "title": "Total Upload Request",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(storefs_upload_object_start_total{}[$__rate_interval]))",
       "legendFormat": "Upload Request"
      }
     ]
    },
    {
     "title": "Total Upload Complete",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(storefs_upload_object_complete_total{}[$__rate_interval]))",
       "legendFormat": "Upload Complete"
      }
     ]
    },
    {
     "title": "Total Upload Processing",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(storefs_upload_object_start_total{}) - sum(storefs_upload_object_complete_total{})",
       "legendFormat": "Upload Processing"
      }
     ]
    },
    {
     "title": "Total Download Request",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(storefs_download_object_start_total{}[$__rate_interval]))",
       "legendFormat": "Download Request"
      }
     ]
    },
    {
     "title": "Total Download Complete",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(storefs_download_object_complete_total{}[$__rate_interval]))",
       "legendFormat": "Download Complete"
      }
     ]
    },
    {
     "title": "Total Download Processing",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(storefs_download_object_start_total{}) - sum(storefs_download_object_complete_total{})",
       "legendFormat": "Download Processing"
      }
     ]
    },
    {
     "title": "Total Object Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(storefs_upload_object_start_total{}[$__rate_interval]))",
       "legendFormat": "Upload"
      },
      {
       "expr": "sum(increase(storefs_download_object_start_total{}[$__rate_interval]))",
       "legendFormat": "Download"
      },
      {
       "expr": "sum(storefs_upload_object_start_total{} - storefs_upload_object_complete_total{}) + sum(storefs_download_object_start_total{} - storefs_download_object_complete_total{})",
       "legendFormat": "Processing"
      }
     ]
    }
   ]
  },
  {
   "title": "Multipart Task",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "panels": [
    {
     "title": "Total CreateMultipart Request",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(storefs_create_multipart_start_total{}[$__rate_interval]))",
       "legendFormat": "CreateMultipart Request"
      }
     ]
    },
    {
     "title": "Total CreateMultipart Complete",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(storefs_create_multipart_complete_total{}[$__rate_interval]))",
       "legendFormat": "CreateMultipart Complete"
      }
     ]
    },
    {
     "title": "Total CreateMultipart Processing",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(storefs_create_multipart_start_total{}) - sum(storefs_create_multipart_complete_total{})",
       "legendFormat": "CreateMultipart Processing"
      }
     ]
    },
    {
     "title": "Total UploadPart Request",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(storefs_upload_part_start_total{}[$__rate_interval]))",
       "legendFormat": "UploadPart Request"
      }
     ]
    },
    {
     "title": "Total UploadPart Complete",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(storefs_upload_part_complete_total{}[$__rate_interval]))",
       "legendFormat": "UploadPart Complete"
      }
     ]
    },
    {
     "title": "Total UploadPart Processing",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(storefs_upload_part_start_total{}) - sum(storefs_upload_part_complete_total{})",
       "legendFormat": "UploadPart Processing"
      }
     ]
    },
    {
     "title": "Total CompleteParts Request",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(storefs_complete_parts_start_total{}[$__rate_interval]))",
       "legendFormat": "CompleteParts Request"
      }
     ]
    },
    {
     "title": "Total CompleteParts Complete",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(storefs_complete_parts_complete_total{}[$__rate_interval]))",
       "legendFormat": "CompleteParts Complete"
      }
     ]
    },
    {
     "title": "Total CompleteParts Processing",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(storefs_complete_parts_start_total{}) - sum(storefs_complete_parts_complete_total{})",
       "legendFormat": "CompleteParts Processing"
      }
     ]
    },
    {
     "title": "Total AbortMultipart Request",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(storefs_abort_multipart_start_total{}[$__rate_interval]))",
       "legendFormat": "AbortMultipart Request"
      }
     ]
    },
    {
     "title": "Total AbortMultipart Complete",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(storefs_abort_multipart_complete_total{}[$__rate_interval]))",
       "legendFormat": "AbortMultipart Complete"
      }
     ]
    },
    {
     "title": "Total AbortMultipart Processing",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(storefs_abort_multipart_start_total{}) - sum(storefs_abort_multipart_complete_total{})",
       "legendFormat": "AbortMultipart Processing"
      }
     ]
    },
    {
     "title": "Total Multipart Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(storefs_create_multipart_start_total{}[$__rate_interval]))",
       "legendFormat": "CreateMultipart"
      },
      {
       "expr": "sum(increase(storefs_upload_part_start_total{}[$__rate_interval]))",
       "legendFormat": "UploadPart"
      },
      {
       "expr": "sum(increase(storefs_complete_parts_start_total{}[$__rate_interval]))",
       "legendFormat": "CompleteParts"
      },
      {
       "expr": "sum(increase(storefs_abort_multipart_start_total{}[$__rate_interval]))",
       "legendFormat": "AbortMultipart"
      },
      {
       "expr": "sum(storefs_create_multipart_start_total{} - storefs_create_multipart_complete_total{}) + sum(storefs_upload_part_start_total{} - storefs_upload_part_complete_total{}) + sum(storefs_complete_parts_start_total{} - storefs_complete_parts_complete_total{}) + sum(storefs_abort_multipart_start_total{} - storefs_abort_multipart_complete_total{})",
       "legendFormat": "Processing"
      }
     ]
    }
   ]
  },
  {
   "title": "Fragment Task",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "panels": [
    {
     "title": "Total Fragment Write Request",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(storefs_write_fragment_start_total{}[$__rate_interval]))",
       "legendFormat": "Write Request"
      }
     ]
    },
    {
     "title": "Total Fragment Write Complete",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(storefs_write_fragment_complete_total{}[$__rate_interval]))",
       "legendFormat": "Write Complete"
      }
     ]
    },
    {
     "title": "Total Fragment Write Processing",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(storefs_write_fragment_start_total{}) - sum(storefs_write_fragment_complete_total{})",
       "legendFormat": "Write Processing"
      }
     ]
    },
    {
     "title": "Total Fragment Read Request",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(storefs_read_fragment_start_total{}[$__rate_interval]))",
       "legendFormat": "Read Request"
      }
     ]
    },
    {
     "title": "Total Fragment Read Complete",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(storefs_read_fragment_complete_total{}[$__rate_interval]))",
       "legendFormat": "Read Complete"
      }
     ]
    },
    {
     "title": "Total Fragment Read Processing",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(storefs_read_fragment_start_total{}) - sum(storefs_read_fragment_complete_total{})",
       "legendFormat": "Read Processing"
      }
     ]
    },
    {
     "title": "Total Fragment Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(storefs_write_fragment_start_total{}[$__rate_interval]))",
       "legendFormat": "Write"
      },
      {
       "expr": "sum(increase(storefs_read_fragment_start_total{}[$__rate_interval]))",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(storefs_write_fragment_start_total{} - storefs_write_fragment_complete_total{}) + sum(storefs_read_fragment_start_total{} - storefs_read_fragment_complete_total{})",
       "legendFormat": "Processing"
      }
     ]
    }
   ]
  },
  {
   "title": "Bucket Task (All Nodes)",
   "type": "row",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 36 },
   "panels": [
    {
     "title": "Top 10 Hot Buckets (Upload, All Nodes)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "topk(10, sum by (bucket) (storefs_upload_hot_bucket_2m))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 10 Hot Buckets (Download, All Nodes)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "targets": [
      {
       "expr": "topk(10, sum by (bucket) (storefs_download_hot_bucket_2m))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 10 Hot Buckets (Upload Part, All Nodes)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "topk(10, sum by (bucket) (storefs_upload_part_hot_bucket_2m))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 10 Hot Buckets (Multipart Complete, All Nodes)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "topk(10, sum by (bucket) (storefs_multipart_complete_hot_bucket_2m))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Cluster Resource Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Free Disk by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (node) (storefs_disk_usage_percent{}))",
     "legendFormat": "{{node}} free"
    }
   ]
  },
  {
   "title": "CPU by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (node) (storefs_cpu_usage_percent{})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (node) (storefs_memory_usage_percent{})",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}