ADMIN SET FRONTEND CONFIG ("enable_experimental_gin" = "true");
SET GLOBAL new_planner_optimize_timeout = 60000;

CREATE DATABASE mydb;
USE mydb;

CREATE TABLE IF NOT EXISTS policies
(
    id            BIGINT       NOT NULL,
    name          VARCHAR(128) NOT NULL,
    type          VARCHAR(16)  NOT NULL,
    replicas      INT,
    data_shards   INT,
    parity_shards INT,
    created_at    DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX index_policies_name (name) USING GIN
) PRIMARY KEY(id)
DISTRIBUTED BY HASH(id) BUCKETS 3
PROPERTIES (
    "replication_num" = "1"
);

CREATE TABLE IF NOT EXISTS user_groups
(
    id                BIGINT       NOT NULL COMMENT 'group unique id (generated by GenerateID)',
    name              VARCHAR(128) NOT NULL COMMENT 'group name (unique)',
    default_policy_id BIGINT COMMENT 'default policy id for this group',
    created_at        DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    INDEX index_user_groups_default_policy_id (default_policy_id) USING BITMAP,
    INDEX index_user_groups_name (name) USING GIN
) PRIMARY KEY (id)
DISTRIBUTED BY HASH(id) BUCKETS 3
PROPERTIES (
    "replication_num" = "1"
);

CREATE TABLE IF NOT EXISTS users
(
    id                   BIGINT COMMENT 'user unique id (generated by GenerateID)',
    name                 VARCHAR(128) NOT NULL COMMENT 'user name (unique)',
    password             VARCHAR(256) NOT NULL COMMENT 'hashed password',
    accesskey            VARCHAR(64)  NOT NULL COMMENT 'access key for API',
    secretkey            VARCHAR(64)  NOT NULL COMMENT 'secret key for API',
    role                 VARCHAR(32)  NOT NULL COMMENT 'user role: user / group_admin / super_admin',
    group_id             BIGINT       NOT NULL COMMENT 'associated group id',
    must_change_password BOOLEAN      NOT NULL DEFAULT '0' COMMENT 'must change password on next login',
    bypass               BOOLEAN      NOT NULL DEFAULT '0' COMMENT 'IAM s3:BypassGovernanceRetention',
    mfa_secret           VARCHAR(512) NOT NULL DEFAULT '' COMMENT 'encrypted TOTP secret (AES-256-GCM)',
    mfa_enabled          BOOLEAN      NOT NULL DEFAULT '0' COMMENT 'MFA enabled flag',
    created_at           DATETIME              DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    INDEX index_users_group_id (group_id) USING BITMAP,
    INDEX index_users_name (name) USING GIN,
    INDEX index_users_accesskey (accesskey) USING GIN,
    INDEX index_users_role (role) USING BITMAP
) PRIMARY KEY (id)
DISTRIBUTED BY HASH(id) BUCKETS 3
PROPERTIES (
    "enable_persistent_index" = "true",
    "replication_num" = "1"
);

CREATE TABLE IF NOT EXISTS buckets
(
    id               BIGINT COMMENT 'bucket unique id (generated by GenerateID)',
    name             VARCHAR(128) NOT NULL COMMENT 'bucket name (unique)',
    policy_id        BIGINT       NOT NULL COMMENT 'associated policy id',
    owner_id         BIGINT       NOT NULL COMMENT 'owner user id',
    versioning       VARCHAR(64)  NOT NULL DEFAULT 'Unversioned' COMMENT 'versioning status: Unversioned/Enabled/Suspended',
    is_encrypted     BOOLEAN      NOT NULL DEFAULT '1' COMMENT 'encryption on/off (deprecated, use encryption_type)',
    encryption_type  VARCHAR(16)  NOT NULL DEFAULT 'sse-s3' COMMENT 'encryption type: none/sse-s3/sse-kms',
    kms_key_id       VARCHAR(256) NOT NULL DEFAULT '' COMMENT 'KMS CMK key ID (KMIP Unique Identifier)',
    bucket_key       VARCHAR(512) NOT NULL DEFAULT '' COMMENT 'wrapped Bucket Key (base64)',
    bucket_key_context VARCHAR(512) NOT NULL DEFAULT '' COMMENT 'Bucket Key encryption context (JSON)',
    bucket_key_id    VARCHAR(64)  NOT NULL DEFAULT '' COMMENT 'Bucket Key version identifier',
    is_locked        BOOLEAN      NOT NULL DEFAULT '0' COMMENT 'object lock on/off',
    lock_mode        VARCHAR(128) NOT NULL DEFAULT 'COMPLIANCE' COMMENT 'object lock mode: COMPLIANCE/GOVERNANCE',
    retention        BIGINT       NOT NULL DEFAULT '30' COMMENT 'retention days',
    is_public        BOOLEAN      NOT NULL DEFAULT '0' COMMENT 'public bucket flag',
    last_update_at   DATETIME              DEFAULT CURRENT_TIMESTAMP COMMENT 'last update time',
    created_at       DATETIME              DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    INDEX index_buckets_name (name) USING GIN,
    INDEX index_buckets_policy_id (policy_id) USING BITMAP,
    INDEX index_buckets_owner_id (owner_id) USING BITMAP,
    INDEX index_buckets_encryption_type (encryption_type) USING BITMAP
) PRIMARY KEY (id)
DISTRIBUTED BY HASH(id) BUCKETS 3 PROPERTIES (
    "enable_persistent_index" = "true",
    "replication_num" = "1"
);

CREATE TABLE IF NOT EXISTS bucket_tags
(
    bucket_id            BIGINT       NOT NULL,
    tag_key              VARCHAR(128) NOT NULL,
    tag_value            VARCHAR(256) NOT NULL,
    normalized_tag_key   VARCHAR(128) NOT NULL COMMENT 'lowercase for case-insensitive search',
    normalized_tag_value VARCHAR(256) NOT NULL COMMENT 'lowercase for case-insensitive search',
    created_at           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX index_bucket_tags_key (tag_key) USING BITMAP,
    INDEX index_bucket_tags_normalized_key (normalized_tag_key) USING GIN
) PRIMARY KEY (bucket_id, tag_key)
DISTRIBUTED BY HASH(bucket_id) BUCKETS 3
PROPERTIES ("compression" = "zstd", "replication_num" = "1");

CREATE TABLE IF NOT EXISTS bucket_acls
(
    id            BIGINT       NOT NULL COMMENT 'ACL entry unique id (generated by GenerateID)',
    bucket_id     BIGINT       NOT NULL COMMENT 'bucket id',
    grantee       VARCHAR(256) NOT NULL COMMENT 'grantee identifier: user ID for canonical_user, or URI for AllUsers/AuthenticatedUsers',
    grantee_type  VARCHAR(32)  NOT NULL COMMENT 'grantee type: canonical_user | all_users | authenticated_users',
    permission    VARCHAR(32)  NOT NULL COMMENT 'S3 permission: FULL_CONTROL | WRITE | READ | READ_ACP | WRITE_ACP',
    created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX index_bucket_acls_bucket_id (bucket_id) USING BITMAP
) PRIMARY KEY (id)
DISTRIBUTED BY HASH(id) BUCKETS 3
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS object_md
(
    bucket_id        BIGINT        NOT NULL COMMENT 'bucket id',
    obj_name_hash    LARGEINT      NOT NULL COMMENT 'hash of object name, to accelarate searching',
    object_name      VARCHAR(1024) NOT NULL COMMENT 'object name',
    policy_id        BIGINT        NOT NULL COMMENT 'policy id',
    enc_key          VARCHAR(1024) NOT NULL DEFAULT '' COMMENT 'encryption key (hex for SSE-S3/SSE-C, base64 wrapped DEK for SSE-KMS)',
    is_sse_c         BOOLEAN       NOT NULL DEFAULT '0' COMMENT 'if it is ssec (deprecated, use encryption_mode)',
    encryption_mode  VARCHAR(16)   NOT NULL DEFAULT 'sse-s3' COMMENT 'encryption mode: sse-s3/sse-c/sse-kms',
    kms_key_context  VARCHAR(512)  NOT NULL DEFAULT '' COMMENT 'KMS encryption context (JSON)',
    has_version      BOOLEAN       NOT NULL DEFAULT '0' COMMENT 'if it has versions in object_v_md table',
    is_deleted       BOOLEAN       NOT NULL DEFAULT '0' COMMENT 'delete marker',
    id               BIGINT        NOT NULL COMMENT 'object unique id (generated by GenerateID)',
    size             BIGINT        NOT NULL COMMENT 'object size in bytes',
    crc              VARCHAR(64)   NOT NULL COMMENT 'CRC checksum',
    upload_id        VARCHAR(128)  NOT NULL COMMENT 'upload id',
    write_time       DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'write time',
    lock_mode        VARCHAR(128)  NOT NULL DEFAULT 'COMPLIANCE' COMMENT 'object lock mode: COMPLIANCE/GOVERNANCE',
    expiration_time  DATETIME COMMENT 'lock expiration time',
    lifecycle_expiration_time DATETIME COMMENT 'lifecycle expiration time (independent of lock expiration_time)',
    created_at       DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    status           VARCHAR(32)   NOT NULL DEFAULT 'pending' COMMENT 'write status: pending/completed/failure/interrupted',
    INDEX index_object_md_object_name (object_name) USING GIN,
    INDEX index_object_md_status (status) USING BITMAP,
    INDEX index_object_md_encryption_mode (encryption_mode) USING BITMAP
) PRIMARY KEY (bucket_id, obj_name_hash, object_name)
DISTRIBUTED BY HASH(bucket_id) BUCKETS 32 PROPERTIES (
    "compression" = "zstd",
    "enable_persistent_index" = "true",
    "bloom_filter_columns" = "id",
    "replication_num" = "1"
);

CREATE TABLE IF NOT EXISTS object_v_md
(
    bucket_id       BIGINT        NOT NULL COMMENT 'bucket id',
    obj_name_hash LARGEINT NOT NULL COMMENT 'hash of object name, to accelarate searching',
    object_name     VARCHAR(1024) NOT NULL COMMENT 'object name',
    version         VARCHAR(36) COMMENT 'version (uuid)',
    is_latest       BOOLEAN       NOT NULL DEFAULT '0' COMMENT 'is latest version',
    is_deleted      BOOLEAN       NOT NULL DEFAULT '0' COMMENT 'delete marker',
    policy_id       BIGINT        NOT NULL COMMENT 'policy id',
    enc_key          VARCHAR(1024) NOT NULL DEFAULT '' COMMENT 'encryption key (hex for SSE-S3/SSE-C, base64 wrapped DEK for SSE-KMS)',
    is_sse_c         BOOLEAN       NOT NULL DEFAULT '0' COMMENT 'if it is ssec (deprecated, use encryption_mode)',
    encryption_mode  VARCHAR(16)   NOT NULL DEFAULT 'sse-s3' COMMENT 'encryption mode: sse-s3/sse-c/sse-kms',
    kms_key_context  VARCHAR(512)  NOT NULL DEFAULT '' COMMENT 'KMS encryption context (JSON)',
    id              BIGINT        NOT NULL COMMENT 'object unique id (generated by GenerateID)',
    size            BIGINT        NOT NULL COMMENT 'object size in bytes',
    crc             VARCHAR(64)   NOT NULL COMMENT 'CRC checksum',
    upload_id       VARCHAR(128)  NOT NULL COMMENT 'upload id',
    write_time      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'write time',
    lock_mode       VARCHAR(128)  NOT NULL DEFAULT 'COMPLIANCE' COMMENT 'object lock mode: COMPLIANCE/GOVERNANCE',
    expiration_time DATETIME COMMENT 'lock expiration time',
    lifecycle_expiration_time DATETIME COMMENT 'lifecycle expiration time (independent of lock expiration_time)',
    created_at      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    status          VARCHAR(32)   NOT NULL DEFAULT 'pending' COMMENT 'write status: pending/completed/failure/interrupted',
    INDEX index_object_v_md_object_name (object_name) USING GIN,
    INDEX index_object_v_md_encryption_mode (encryption_mode) USING BITMAP,
    INDEX index_object_v_md_status (status) USING BITMAP
) PRIMARY KEY (bucket_id, obj_name_hash, object_name, version)
DISTRIBUTED BY HASH(bucket_id) BUCKETS 32 PROPERTIES (
    "compression" = "zstd",
    "enable_persistent_index" = "true",
    "bloom_filter_columns" = "id",
    "replication_num" = "1"
);

CREATE TABLE IF NOT EXISTS object_tags
(
    bucket_id            BIGINT        NOT NULL,
    obj_name_hash        LARGEINT      NOT NULL,
    object_name          VARCHAR(1024) NOT NULL,
    version              VARCHAR(36)   NOT NULL DEFAULT 'null',
    tag_key              VARCHAR(128)  NOT NULL,
    tag_value            VARCHAR(256)  NOT NULL,
    normalized_tag_key   VARCHAR(128)  NOT NULL COMMENT 'lowercase for case-insensitive search',
    normalized_tag_value VARCHAR(256)  NOT NULL COMMENT 'lowercase for case-insensitive search',
    created_at           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX index_object_tags_key (tag_key) USING BITMAP,
    INDEX index_object_tags_normalized_key (normalized_tag_key) USING GIN
) PRIMARY KEY (bucket_id, obj_name_hash, object_name, version, tag_key)
DISTRIBUTED BY HASH(bucket_id) BUCKETS 32
PROPERTIES ("compression" = "zstd", "replication_num" = "1");

CREATE TABLE IF NOT EXISTS fragment_md
(
    object_id     BIGINT        NOT NULL COMMENT 'object id',
    fragment_id   INT           NOT NULL COMMENT 'fragment id',
    shard_id      INT           NOT NULL COMMENT 'shard id',
    node_name     VARCHAR(128)  NOT NULL COMMENT 'node name',
    node_ip       VARCHAR(64)   NOT NULL COMMENT 'node ip address',
    disk_dir      VARCHAR(1024) NOT NULL COMMENT 'disk directory',
    path          VARCHAR(2048) NOT NULL COMMENT 'full path to fragment',
    fragment_size BIGINT        NOT NULL COMMENT 'fragment size in bytes',
    crc           VARCHAR(64)   NOT NULL COMMENT 'CRC checksum',
    write_time    DATETIME      NOT NULL COMMENT 'write time',
    created_at    DATETIME               DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    status        VARCHAR(32)   NOT NULL DEFAULT 'pending' COMMENT 'write status: pending/completed/failure/interrupted',
    INDEX index_fragment_md_status (status) USING BITMAP,
    INDEX index_fragment_md_node_name(node_name) USING BITMAP
) PRIMARY KEY (object_id, fragment_id, shard_id, node_name)
DISTRIBUTED BY HASH(object_id) BUCKETS 64 PROPERTIES (
    "compression" = "zstd",
    "enable_persistent_index" = "true",
    "replication_num" = "1"
);

CREATE TABLE IF NOT EXISTS multipart_uploads
(
    bucket_id        BIGINT        NOT NULL COMMENT 'associated bucket id',
    obj_name_hash    LARGEINT      NOT NULL COMMENT 'hash of object name, to accelarate searching',
    object_name      VARCHAR(1024) NOT NULL COMMENT 'object name',
    upload_id        VARCHAR(128)  NOT NULL COMMENT 'unique upload id',
    policy_id        BIGINT        NOT NULL COMMENT 'policy id',
    enc_key          VARCHAR(1024) NOT NULL DEFAULT '' COMMENT 'encryption key (hex for SSE-S3/SSE-C, base64 wrapped DEK for SSE-KMS)',
    is_sse_c         BOOLEAN       NOT NULL DEFAULT '0' COMMENT 'if it is ssec (deprecated, use encryption_mode)',
    encryption_mode  VARCHAR(16)   NOT NULL DEFAULT 'sse-s3' COMMENT 'encryption mode: sse-s3/sse-c/sse-kms',
    kms_key_context  VARCHAR(512)  NOT NULL DEFAULT '' COMMENT 'KMS encryption context (JSON)',
    initiated_time   DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT 'initiated time',
    completed_time  DATETIME COMMENT 'completed time',
    status          VARCHAR(32)   NOT NULL DEFAULT 'active' COMMENT 'status: active/completed/aborted',
    created_at      DATETIME               DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    lock_mode       VARCHAR(128)  NOT NULL DEFAULT 'COMPLIANCE' COMMENT 'object lock mode: COMPLIANCE/GOVERNANCE',
    expiration_time DATETIME COMMENT 'lock expiration time',
    tags            JSON COMMENT 'tag list: [{"Key":"k","Value":"v"},...]',
    normalized_tags JSON COMMENT 'lowercased tag list for case-insensitive search',
    INDEX index_multipart_uploads_status (status) USING BITMAP,
    INDEX index_multipart_uploads_encryption_mode (encryption_mode) USING BITMAP
) PRIMARY KEY (bucket_id, obj_name_hash, object_name, upload_id)
DISTRIBUTED BY HASH(bucket_id) BUCKETS 32 PROPERTIES (
    "compression" = "zstd",
    "enable_persistent_index" = "true",
    "replication_num" = "1"
);

CREATE TABLE IF NOT EXISTS parts
(
    upload_id   VARCHAR(128) NOT NULL COMMENT 'associated upload id',
    part_number INT          NOT NULL COMMENT 'part number (1-based)',
    id          BIGINT       NOT NULL COMMENT 'part unique id',
    size        BIGINT       NOT NULL COMMENT 'part size in bytes',
    crc         VARCHAR(64)  NOT NULL COMMENT 'CRC checksum',
    upload_time DATETIME              DEFAULT CURRENT_TIMESTAMP COMMENT 'upload time',
    status      VARCHAR(32)  NOT NULL DEFAULT 'pending' COMMENT 'status: pending/completed/failure/interrupted',
    created_at  DATETIME              DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    INDEX index_parts_status (status) USING BITMAP
) PRIMARY KEY (upload_id, part_number)
DISTRIBUTED BY HASH(upload_id) BUCKETS 32 PROPERTIES (
    "compression" = "zstd",
    "enable_persistent_index" = "true",
    "replication_num" = "1"
);

CREATE TABLE IF NOT EXISTS part_fragments
(
    part_id       BIGINT        NOT NULL COMMENT 'associated part id',
    fragment_id   INT           NOT NULL COMMENT 'fragment id',
    shard_id      INT           NOT NULL COMMENT 'shard id',
    node_name     VARCHAR(128)  NOT NULL COMMENT 'node name',
    id            BIGINT        NOT NULL COMMENT 'part fragment unique id',
    node_ip       VARCHAR(64)   NOT NULL COMMENT 'node ip address',
    disk_dir      VARCHAR(1024) NOT NULL COMMENT 'disk directory',
    path          VARCHAR(2048) NOT NULL COMMENT 'full path to fragment',
    fragment_size BIGINT        NOT NULL COMMENT 'fragment size in bytes',
    crc           VARCHAR(64)   NOT NULL COMMENT 'CRC checksum',
    created_at    DATETIME               DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    status        VARCHAR(32)   NOT NULL DEFAULT 'active' COMMENT 'status: active/completed/aborted',
    INDEX index_part_fragments_status (status) USING BITMAP,
    INDEX index_part_fragments__node_name(node_name) USING BITMAP
) PRIMARY KEY (part_id, fragment_id, shard_id, node_name)
DISTRIBUTED BY HASH(part_id) BUCKETS 64 PROPERTIES (
    "compression" = "zstd",
    "enable_persistent_index" = "true",
    "replication_num" = "1"
);

CREATE TABLE IF NOT EXISTS node_status
(
    node_name      VARCHAR(128)  NOT NULL COMMENT 'node name',
    status         VARCHAR(32)   NOT NULL DEFAULT 'active' COMMENT 'status: active/taint',
    operator       BIGINT        NOT NULL COMMENT 'operator id',
    last_update_at DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time'
) PRIMARY KEY (node_name)
DISTRIBUTED BY HASH(node_name) BUCKETS 3 PROPERTIES (
    "replication_num" = "1"
);

CREATE TABLE IF NOT EXISTS tasks (
    id                BIGINT       NOT NULL,
    name              VARCHAR(256) NOT NULL,
    type              VARCHAR(64)  NOT NULL,
    status            VARCHAR(32)  NOT NULL DEFAULT 'pending',
    node_name         VARCHAR(128),
    params            TEXT,
    output            TEXT,
    error_message     TEXT,
    progress          INT          NOT NULL DEFAULT '0',
    started_at        DATETIME,
    completed_at      DATETIME,
    created_by        BIGINT       NOT NULL,
    created_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_tasks_status(status) USING BITMAP,
    INDEX idx_tasks_type(type) USING BITMAP,
    INDEX idx_tasks_node_name(node_name) USING BITMAP
) PRIMARY KEY(id)
DISTRIBUTED BY HASH(id) BUCKETS 16;

CREATE TABLE IF NOT EXISTS bucket_notifications
(
    id             BIGINT       NOT NULL COMMENT 'notification unique id (generated by GenerateID)',
    bucket_id      BIGINT       NOT NULL COMMENT 'associated bucket id',
    url            VARCHAR(2048) NOT NULL COMMENT 'Webhook endpoint URL',
    secret         VARCHAR(512) DEFAULT '' COMMENT 'HMAC-SHA256 signing secret',
    events         VARCHAR(512) NOT NULL DEFAULT 's3:ObjectCreated:*' COMMENT 'event types, comma-separated',
    filter_prefix  VARCHAR(1024) DEFAULT '' COMMENT 'object key prefix filter',
    filter_suffix  VARCHAR(1024) DEFAULT '' COMMENT 'object key suffix filter',
    format         VARCHAR(16)  DEFAULT 'native' COMMENT 'payload format: native or aws',
    enabled        BOOLEAN      DEFAULT '1' COMMENT 'enable/disable this notification',
    retry_count    INT          DEFAULT '10' COMMENT 'max retry count',
    retry_interval INT          DEFAULT '1' COMMENT 'initial retry backoff seconds',
    created_at     DATETIME     DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    last_update_at DATETIME     DEFAULT CURRENT_TIMESTAMP COMMENT 'last update time',
    INDEX idx_bucket_notifications_bucket_id (bucket_id) USING BITMAP
) PRIMARY KEY (id)
DISTRIBUTED BY HASH(id) BUCKETS 3
PROPERTIES (
    "replication_num" = "1"
);

CREATE TABLE IF NOT EXISTS notification_queue
(
    id              BIGINT       NOT NULL COMMENT 'Snowflake ID, globally ordered',
    noti_config_id  BIGINT       NOT NULL COMMENT 'FK → bucket_notifications.id',
    url             VARCHAR(2048) NOT NULL COMMENT 'Webhook endpoint (denormalized)',
    payload         TEXT         NOT NULL COMMENT 'pre-built JSON body',
    header_event    VARCHAR(64)  NOT NULL COMMENT 'X-StoreFS-Event header value',
    header_event_id VARCHAR(64)  NOT NULL COMMENT 'X-StoreFS-Event-ID header value',
    signature       VARCHAR(128) DEFAULT '' COMMENT 'X-StoreFS-Signature header value',
    status          VARCHAR(16)  NOT NULL DEFAULT 'pending' COMMENT 'pending|delivering|completed|failed|discarded',
    owner_node      VARCHAR(128) DEFAULT '' COMMENT 'node currently responsible for delivery',
    retry_count     INT          DEFAULT '0' COMMENT 'retry attempts so far',
    max_retries     INT          DEFAULT '10' COMMENT 'max retry count from config',
    next_retry_at   DATETIME     NULL COMMENT 'earliest time allowed for next retry',
    last_error      TEXT         NULL COMMENT 'last failure reason',
    ttl_expires_at  DATETIME     NOT NULL COMMENT 'row expires at this time, will be discarded afterwards',
    created_at      DATETIME     DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    last_update_at  DATETIME     DEFAULT CURRENT_TIMESTAMP COMMENT 'last update time',
    INDEX idx_nq_owner_node (owner_node) USING BITMAP,
    INDEX idx_nq_status (status) USING BITMAP
) PRIMARY KEY (id)
DISTRIBUTED BY HASH(id) BUCKETS 3
PROPERTIES (
    "replication_num" = "1"
);

CREATE TABLE IF NOT EXISTS audit_log
(
    id                 BIGINT        NOT NULL COMMENT 'Snowflake ID',
    timestamp          DATETIME      NOT NULL COMMENT 'Request received time (UTC)',
    source_ip          VARCHAR(45)   NOT NULL COMMENT 'Client IP address',
    http_method        VARCHAR(10)   NOT NULL COMMENT 'HTTP method',
    path               VARCHAR(2048) NOT NULL COMMENT 'Request path',
    query_string       VARCHAR(2048) DEFAULT '' COMMENT 'Query string',
    user_identity      VARCHAR(256)  NOT NULL COMMENT 'Authenticated user name, or anonymous',
    status_code        INT           NOT NULL COMMENT 'HTTP response status code',
    duration_ms        BIGINT        NOT NULL COMMENT 'Request processing time in ms',
    request_id         VARCHAR(64)   NOT NULL COMMENT 'Unique request ID for tracing',
    operation_type     VARCHAR(128)  NOT NULL COMMENT 'S3 operation or admin operation name',
    error_code         VARCHAR(64)   DEFAULT '' COMMENT 'Error code if any',
    bucket_name        VARCHAR(128)  DEFAULT '' COMMENT 'S3 bucket name',
    object_key         VARCHAR(1024) DEFAULT '' COMMENT 'S3 object key',
    resource_type      VARCHAR(32)   DEFAULT '' COMMENT 's3 或 admin',
    target_resource_id VARCHAR(64)   DEFAULT '' COMMENT 'Target resource ID for admin operations',
    action_details     TEXT          COMMENT 'JSON string with additional action details',
    created_at         DATETIME      DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation time',
    INDEX idx_audit_timestamp (timestamp) USING BITMAP,
    INDEX idx_audit_operation_type (operation_type) USING BITMAP,
    INDEX idx_audit_user_identity (user_identity) USING BITMAP,
    INDEX idx_audit_bucket_name (bucket_name) USING BITMAP,
    INDEX idx_audit_status_code (status_code) USING BITMAP,
    INDEX idx_audit_request_id (request_id) USING GIN
) PRIMARY KEY (id, timestamp)
PARTITION BY RANGE(timestamp)
(
    PARTITION p20260729 VALUES LESS THAN ("2026-07-30")
)
DISTRIBUTED BY HASH(id) BUCKETS 3
PROPERTIES (
    "replication_num" = "1",
    "compression" = "zstd"
);

CREATE TABLE IF NOT EXISTS dir_entries
(
    bucket_id   BIGINT        NOT NULL COMMENT 'bucket id',
    parent_path VARCHAR(1024) NOT NULL COMMENT 'parent directory path, e.g. "" or "dir1/subdir"',
    name        VARCHAR(1024) NOT NULL COMMENT 'directory name, e.g. "subdir"',
    size        BIGINT        NOT NULL DEFAULT '0' COMMENT 'number of direct children (files + subdirs)',
    mtime       DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'modification time'
) PRIMARY KEY (bucket_id, parent_path, name)
DISTRIBUTED BY HASH(bucket_id) BUCKETS 32
PROPERTIES (
    "replication_num" = "1"
);

CREATE TABLE IF NOT EXISTS kms_config
(
    id                   BIGINT       NOT NULL COMMENT 'Snowflake ID',
    name                 VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'friendly config name',
    description          VARCHAR(512) NOT NULL DEFAULT '' COMMENT 'description',
    provider             VARCHAR(32)  NOT NULL DEFAULT 'kmip' COMMENT 'provider type: kmip, future: aws, azure, gcp, vault',
    provider_config      TEXT         NOT NULL DEFAULT '' COMMENT 'provider-specific config (JSON), e.g. {"region":"us-east-1"}',
    endpoint             VARCHAR(256) NOT NULL DEFAULT '' COMMENT 'KMS server address: host:port',
    username             VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'KMIP auth username',
    password             VARCHAR(256) NOT NULL DEFAULT '' COMMENT 'KMIP auth password (encrypted)',
    client_cert          TEXT         NOT NULL COMMENT 'TLS client certificate (PEM)',
    client_key           TEXT         NOT NULL COMMENT 'TLS client key (PEM, encrypted)',
    ca_cert              TEXT         NOT NULL COMMENT 'CA certificate (PEM)',
    timeout              INT          NOT NULL DEFAULT '10' COMMENT 'KMIP request timeout in seconds',
    health_check_interval INT         NOT NULL DEFAULT '30' COMMENT 'health check interval in seconds',
    allow_degraded_reads BOOLEAN      NOT NULL DEFAULT '0' COMMENT 'allow reads with expired BK cache when KMS offline',
    created_at           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
) PRIMARY KEY (id)
DISTRIBUTED BY HASH(id) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS kms_keys
(
    id              BIGINT       NOT NULL COMMENT 'Snowflake ID',
    kms_config_id   BIGINT       NOT NULL DEFAULT '0' COMMENT 'FK to kms_config.id',
    key_id          VARCHAR(256) NOT NULL COMMENT 'KMS key identifier (KMIP Unique Identifier)',
    alias           VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'friendly alias',
    description     VARCHAR(512) NOT NULL DEFAULT '' COMMENT 'description',
    provider        VARCHAR(32)  NOT NULL DEFAULT 'kmip' COMMENT 'kms provider: kmip',
    group_id        BIGINT       NOT NULL DEFAULT '0' COMMENT '0=global key, >0=group key',
    status          VARCHAR(32)  NOT NULL DEFAULT 'enabled' COMMENT 'enabled/retired/disabled/pending_deletion',
    retired_at      DATETIME     COMMENT 'when this key was retired (set on rotate)',
    created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_kms_keys_status (status) USING BITMAP,
    INDEX idx_kms_keys_key_id (key_id) USING GIN,
    INDEX idx_kms_keys_config_id (kms_config_id) USING BITMAP,
    INDEX idx_kms_keys_group_id (group_id) USING BITMAP
) PRIMARY KEY (id)
DISTRIBUTED BY HASH(id) BUCKETS 3
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS cluster_config
(
    ckey   VARCHAR(128) NOT NULL COMMENT 'config key',
    cvalue TEXT         NOT NULL COMMENT 'config value',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'create time'
) PRIMARY KEY (ckey)
DISTRIBUTED BY HASH(ckey) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS mfa_backup_codes
(
    id         BIGINT       NOT NULL COMMENT 'unique id (generated by GenerateID)',
    user_id    BIGINT       NOT NULL COMMENT 'user id (FK to users)',
    code_hash  VARCHAR(64)  NOT NULL COMMENT 'SHA-256 hash of backup code',
    is_used    BOOLEAN      NOT NULL DEFAULT '0' COMMENT 'whether this code has been used',
    created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    INDEX index_mfa_backup_codes_user_id (user_id) USING BITMAP,
    INDEX index_mfa_backup_codes_is_used (is_used) USING BITMAP
) PRIMARY KEY (id)
DISTRIBUTED BY HASH(id) BUCKETS 3
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS personal_access_tokens
(
    id           BIGINT       NOT NULL COMMENT 'unique id (generated by GenerateID)',
    user_id      BIGINT       NOT NULL COMMENT 'user id (FK to users)',
    token_prefix VARCHAR(16)  NOT NULL COMMENT 'first 8 chars of token after prefix for identification',
    token_hash   VARCHAR(64)  NOT NULL COMMENT 'SHA-256 hash of full token',
    description  VARCHAR(256) NOT NULL DEFAULT '' COMMENT 'user-provided description',
    last_used_at DATETIME     COMMENT 'last usage timestamp',
    is_disabled  BOOLEAN      NOT NULL DEFAULT '0' COMMENT 'disabled by user',
    expires_at   DATETIME     COMMENT 'expiration timestamp (NULL = never)',
    created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    INDEX index_pat_user_id (user_id) USING BITMAP
) PRIMARY KEY (id)
DISTRIBUTED BY HASH(id) BUCKETS 3
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS token_blacklist
(
    jti        VARCHAR(64)  NOT NULL COMMENT 'JWT ID (token unique identifier)',
    user_id    BIGINT       NOT NULL COMMENT 'user id (FK to users)',
    revoked_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'revocation timestamp',
    expires_at DATETIME     NOT NULL COMMENT 'JWT original expiry (for auto-cleanup)',
    reason     VARCHAR(64)  NOT NULL DEFAULT '' COMMENT 'revocation reason: logout / password_change / admin_revoke / mfa_disable',
    INDEX index_tb_user (user_id) USING BITMAP,
    INDEX index_tb_expires (expires_at) USING BITMAP
) PRIMARY KEY (jti)
DISTRIBUTED BY HASH(jti) BUCKETS 3
PROPERTIES (
    "enable_persistent_index" = "true",
    "replication_num" = "1"
);

CREATE TABLE IF NOT EXISTS bucket_lifecycle_rules
(
    bucket_id             BIGINT        NOT NULL COMMENT 'bucket id (part of primary key)',
    rule_id               VARCHAR(256)  NOT NULL DEFAULT '' COMMENT 'rule ID (user-defined, unique within bucket)',
    id                    BIGINT        NOT NULL COMMENT 'rule id (deprecated, no longer used as key)',
    status                VARCHAR(32)   NOT NULL DEFAULT 'Enabled' COMMENT 'rule status: Enabled / Disabled',
    filter_prefix         VARCHAR(1024) NOT NULL DEFAULT '' COMMENT 'object prefix filter',
    filter_tags           VARCHAR(2048) NOT NULL DEFAULT '' COMMENT 'filter tags JSON: [{"key":"k","value":"v"}]',
    expiration_days       INT           NOT NULL DEFAULT '0' COMMENT 'expiration days (0 means not set)',
    expiration_date       DATETIME      NULL COMMENT 'expiration date (mutually exclusive with days)',
    expired_del_marker    BOOLEAN       NOT NULL DEFAULT '0' COMMENT 'expired object delete marker',
    noncurrent_days       INT           NOT NULL DEFAULT '0' COMMENT 'noncurrent version expiration days',
    noncurrent_newer      INT           NOT NULL DEFAULT '0' COMMENT 'newer noncurrent versions to retain',
    abort_incomplete_days INT           NOT NULL DEFAULT '0' COMMENT 'abort incomplete multipart upload days',
    priority              INT           NOT NULL DEFAULT '0' COMMENT 'rule priority (lower = higher priority)',
    created_at            DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    updated_at            DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'update time',
    INDEX index_tb_bucket_lifecycle_rules_id (id) USING BITMAP
) PRIMARY KEY(bucket_id, rule_id)
DISTRIBUTED BY HASH(bucket_id) BUCKETS 10
PROPERTIES (
    "replication_num" = "1"
);

INSERT INTO user_groups (id, name, default_policy_id)
VALUES (1, 'default', NULL);

INSERT INTO users (id,
                   name,
                   password,
                   accesskey,
                   secretkey,
                   role,
                   group_id,
                   must_change_password,
                   bypass)
VALUES (1,
        'admin',
        'admin123',
        'admin-ak',
        'admin-sk',
        'super_admin',
        0,
        '1',
        '0');
        
INSERT INTO cluster_config (ckey, cvalue)
SELECT 'jwt_secret', SUBSTR(REPLACE(UUID(), '-', ''), 1, 32)
WHERE NOT EXISTS (SELECT 1 FROM cluster_config WHERE ckey = 'jwt_secret');
