CREATE DATABASE mydb;
USE mydb;

CREATE TABLE IF NOT EXISTS policies (
    id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    type VARCHAR(16) NOT NULL,
    replicas INT,
    data_shards INT,
    parity_shards INT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
)
PRIMARY KEY(id)
DISTRIBUTED BY HASH(id) BUCKETS 3
PROPERTIES (
    "replication_num" = "1"
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT COMMENT 'user unique id (generated by GenerateID)',
    name VARCHAR(128) NOT NULL COMMENT 'user name (unique)',
    password VARCHAR(256) NOT NULL COMMENT 'hashed password',
    accesskey VARCHAR(64) NOT NULL COMMENT 'access key for API',
    secretkey VARCHAR(64) NOT NULL COMMENT 'secret key for API',
    role VARCHAR(32) NOT NULL COMMENT 'user role: admin / normal / ...',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'create time'
)
PRIMARY KEY (id)
DISTRIBUTED BY HASH(id) BUCKETS 3
PROPERTIES (
    "replication_num" = "1"
);

CREATE TABLE IF NOT EXISTS buckets (
    id BIGINT COMMENT 'bucket unique id (generated by GenerateID)',
    name VARCHAR(128) NOT NULL COMMENT 'bucket name (unique)',
    policy_id BIGINT NOT NULL COMMENT 'associated policy id',
    owner_id BIGINT NOT NULL COMMENT 'owner user id',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'create time'
)
PRIMARY KEY (id)
DISTRIBUTED BY HASH(id) BUCKETS 3 PROPERTIES (
    "replication_num" = "1"
);

CREATE TABLE IF NOT EXISTS object_md (
    bucket_id BIGINT NOT NULL COMMENT 'bucket id',
    object_name VARCHAR(1024) NOT NULL COMMENT 'object name',
    policy_id BIGINT NOT NULL COMMENT 'policy id',
    id BIGINT COMMENT 'object unique id (generated by GenerateID)',
    size BIGINT NOT NULL COMMENT 'object size in bytes',
    crc VARCHAR(64) NOT NULL COMMENT 'CRC checksum',
    write_time DATETIME NOT NULL COMMENT 'write time',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    status VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT 'write status: pending/completed/failure'
)
PRIMARY KEY (bucket_id, object_name)
DISTRIBUTED BY HASH(bucket_id) BUCKETS 32 PROPERTIES (
    "replication_num" = "1"
);

CREATE TABLE IF NOT EXISTS fragment_md (
    object_id BIGINT NOT NULL COMMENT 'object id',
    fragment_id INT NOT NULL COMMENT 'fragment id',
    shard_id INT NOT NULL COMMENT 'shard id',
    node_name VARCHAR(128) NOT NULL COMMENT 'node name',
    node_ip VARCHAR(64) NOT NULL COMMENT 'node ip address',
    disk_dir VARCHAR(1024) NOT NULL COMMENT 'disk directory',
    path VARCHAR(2048) NOT NULL COMMENT 'full path to fragment',
    fragment_size BIGINT NOT NULL COMMENT 'fragment size in bytes',
    crc VARCHAR(64) NOT NULL COMMENT 'CRC checksum',
    write_time DATETIME NOT NULL COMMENT 'write time',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    status VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT 'write status: pending/completed/failure'
)
PRIMARY KEY (object_id, fragment_id, shard_id, node_name)
DISTRIBUTED BY HASH(object_id) BUCKETS 64 PROPERTIES (
    "replication_num" = "1"
);

INSERT INTO users (
    id,
    name,
    password,
    accesskey,
    secretkey,
    role
) VALUES (
    1,
    'admin',
    'admin123',
    'admin-ak',
    'admin-sk',
    'admin'
);